# Generated by Django 3.1.4 on 2020-12-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_category_moneytransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='date',
            field=models.DateField(),
        ),
    ]
